name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - stockx-implementation

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run --filter=vite_react_shadcn_ts build

      - name: Add 404 fallback for SPA
        run: cp ./frontend/dist/index.html ./frontend/dist/404.html

      - name: Copy CNAME
        run: cp CNAME ./frontend/dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist